name: Bartosz CI/CD pipeline

on:
    push:
      branches:
        - master
    pull_request:

jobs:
  bartosz:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    permissions:
      checks: write
      pull-requests: write

    steps:
        - name: Checkout latest code from GitHub
          uses: actions/checkout@v4
        
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
            pip install -r requirements.txt